#!/bin/bash

echo "🚀 WhatsApp OTP Setup Guide"
echo "==========================="
echo ""

echo "📋 Current Status Check:"
echo "1. ✅ Server is running on http://localhost:3000"
echo "2. ✅ WhatsApp service is initializing"
echo "3. ⏳ WhatsApp client needs authentication"
echo ""

echo "📱 STEP 1: Initialize WhatsApp Client"
echo "Visit: http://localhost:3000/api/test-whatsapp"
echo "This will start the WhatsApp authentication process"
echo ""

echo "📱 STEP 2: Look for QR Code in Terminal"
echo "After visiting the URL above, check your terminal for a QR code"
echo "It will look like this:"
echo "📱 WhatsApp QR Code:"
echo "████████████████████"
echo "█   █▄▄█   ███   █"
echo "█   █▄▄█   ███   █"
echo "████████████████████"
echo ""

echo "📱 STEP 3: Scan QR Code"
echo "1. Open WhatsApp on your mobile phone"
echo "2. Go to Settings > Linked Devices"
echo "3. Tap 'Link a Device'"
echo "4. Scan the QR code from your terminal"
echo ""

echo "📱 STEP 4: Wait for Authentication"
echo "Look for this message in terminal:"
echo "✅ WhatsApp Client is ready!"
echo ""

echo "📱 STEP 5: Test OTP"
echo "Once authenticated, test with:"
echo "curl -X POST http://localhost:3000/api/auth/forgot-password-otp \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"mobile\":\"9787020525\"}'"
echo ""

echo "🔧 Troubleshooting:"
echo "❌ If no QR code appears:"
echo "   - Check if port 3000 is free"
echo "   - Restart with: npm run dev"
echo "   - Visit /api/test-whatsapp again"
echo ""

echo "❌ If QR code doesn't work:"
echo "   - Clear WhatsApp Web sessions in phone"
echo "   - Delete whatsapp-session/ folder and try again"
echo "   - Restart server"
echo ""

echo "❌ If OTP still fails:"
echo "   - Check phone number format (10 digits)"
echo "   - Ensure user exists in database"
echo "   - Check server logs for errors"
echo ""

echo "🎯 Quick Test Commands:"
echo ""
echo "# Check server status:"
echo "curl http://localhost:3000/api/test-users"
echo ""
echo "# Initialize WhatsApp:"
echo "curl http://localhost:3000/api/test-whatsapp"
echo ""
echo "# Request OTP:"
echo "curl -X POST http://localhost:3000/api/auth/forgot-password-otp -H \"Content-Type: application/json\" -d '{\"mobile\":\"9787020525\"}'"
echo ""

echo "💡 Important Notes:"
echo "- No Meta Portal setup required"
echo "- Uses WhatsApp Web (like browser WhatsApp)"
echo "- QR code authentication is one-time only"
echo "- Session persists until logout"
echo ""

read -p "Press Enter to continue and check terminal for QR code..."
